apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfsshare-sas
  namespace: lab
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.8.4
    path: "/export/pvs/shared-data"
  claimRef:
    namespace: lab
    name: pvc-nfsshare-sas
  storageClassName: sas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfsshare-sas
  namespace: lab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sas-nfs
  resources:
    requests:
      storage: 40Gi
