resources:
- shared-newcasserver-pvc.yaml
- provider-pvc.yaml
- cas-shared-newcasserver-cr.yaml
- transfer-pvc.yaml
generators:
- configmaps.yaml
configurations:
- kustomizeconfig.yaml
transformers:
- cas-fsgroup-security-context.yaml
- annotations.yaml
- backup-agent-patch.yaml
- cas-consul-sidecar.yaml
- node-affinity.yaml
- state-transfer.yaml

