---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-support-state-transfer
patch: |-
  - op: add
    path: /spec/supportStateTransfer
    value: true
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
