apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sas.com/backup-role: "storage"
    app.kubernetes.io/part-of: cas
    sas.com/cas-instance: shared-newcasserver
    sas.com/cas-pvc: transfer
  annotations:
    sas.com/component-name: sas-cas-operator
  name: sas-cas-transfer-data-shared-newcasserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
