apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-microanalytic-score-archive
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi  # change this to desired capacity
  storageClassName: sas-nfs # change this the desired storage class
