apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-risk-modeling-content-data
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: sas-nfs #change this the desired storage class
