apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-model-publish-kaniko
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi  #change this to desired capacity
  storageClassName: sas-nfs # change this the desired storage class
