
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-3b931cb4fe5c7ef4
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-64b40f1b2c952097
patch: |-
  - op: add
    path: /spec/template/spec/initContainers
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-04b31d978e4491b0
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-e29ea2e530528300
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-2ce1b05c0990a374
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-a9aeb41439c1bae2
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-feacafb23bcd804d
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-dd5c7b51c4ce424e
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-729608278d918399
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext/capabilities/add
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-62f5cb6041a10231
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-8c48ac9ac2df1a94
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f482a2bb836beeca
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-18e8e0fdc71bbb71
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-725e52569d29dc36
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-886d63748879ebf7
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-7ed2a2fa62fe96e9
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d596253b6b9fdf2d
patch: |-
  - op: add
    path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/namespaces
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-6803a524056e1c8f
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-4a4af8abf5119499
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-risk-modeling-core
  version: v1
