---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-data-profiles
    sas.com/admin: namespace
  name: sas-data-profiles
spec:
  routes:
  - conditions:
    - prefix: /dataProfiles
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /dataProfiles/
    services:
    - name: sas-data-profiles
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /dataProfiles/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-data-profiles
      port: 80
    timeoutPolicy:
      response: 300s

