apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sas.com/backup-role: "storage"
    app.kubernetes.io/part-of: cas
    sas.com/cas-pvc: backup
  name: sas-cas-backup-data-shared-newcasserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
