# PatchTransformer to make the cas node label required
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: require-affinity-label
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/-
    value:
      key: workload.sas.com/class
      operator: In
      values:
      - cas
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
