apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: sas-microanalytic-score-astores
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
  storageClassName: sas-nfs
